name: Build on Push and Tag

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
    tags:
      - '[45].[0-9]+.[0-9]+*'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
    branches:
      - master

jobs:
  clang_check:
    name: 01 - Code Format Checks
    if: ${{ contains(github.event.head_commit.message, '[skip ci]') != true }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clang-format
        if: ${{ ! always() }}
        run: sudo apt-get install -y clang-format-12

      - name: Run clang-format
        if: ${{ ! always() }}
        run: ./.github/scripts/check-format.sh && ./.github/scripts/check-changes.sh

      - name: Install cmake-format
        run: sudo pip install cmake-format

      - name: Run cmake-format
        run: ./.github/scripts/check-cmake.sh

  windows_build:
    name: 02 - Windows
    runs-on: windows-2019
    strategy:
      fail-fast: true
      matrix:
        arch: [x86, x64]
    if: always()
    needs: clang_check
    outputs:
      commitHash: ${{ steps.setup.outputs.commitHash }}
      versionSuffix: ${{ steps.setup.outputs.versionSuffix }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin
          submodules: recursive

      - name: Checkout obs-studio
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: obs-studio
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        working-directory: ${{ github.workspace }}/plugin
        id: setup
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          Write-Output '::group::Set Commit Information'
          $CommitHash = (git rev-parse HEAD)[0..8] -join ''

          try {
            . ./.github/scripts/utils.pwsh/Invoke-External.ps1
            $Version = Invoke-External git describe --exact-match --tags --abbrev=0 2> $null
            $VersionSuffix = $Version[6..19] -join ''
          } catch {
            $LASTEXITCODE = 0
            $Version = "${CommitHash}-git"
            $VersionSuffix = "-${CommitHash}-git"
          }
          Write-Output '::endgroup::'

          Write-Output "::set-output name=commitHash::${CommitHash}"
          Write-Output "::set-output name=version::${Version}"
          Write-Output "::set-output name=versionSuffix::${VersionSuffix}"

      - name: Check for GitHub Labels
        id: seekingTesters
        working-directory: ${{ github.workspace }}/plugin
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          $LabelFound = try {
            $Params = @{
              Authorization = 'Bearer'
              Token = (ConvertTo-SecureString '${{ secrets.GITHUB_TOKEN }}' -AsPlainText)
              Uri = '${{ github.event.pull_request.url }}'
              UseBasicParsing = $true
            }

            (Invoke-RestMethod @Params).labels.name.contains('Seeking Testers')
          } catch {
            $false
          }

          Write-Output "::set-output name=found::$(([string]${LabelFound}).ToLower())"

      - name: Build Plugin
        uses: ./plugin/.github/actions/build-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          visualStudio: 'Visual Studio 16 2019'
          versionSuffix: ${{ steps.setup.outputs.versionSuffix }}

      - name: Package Plugin
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo

      - name: Upload Build Artifact
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        uses: actions/upload-artifact@v3
        with:
          name: obs-websocket-windows-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}
          path: ${{ github.workspace }}/plugin/release/obs-websocket-*.zip

      - name: Package Plugin Installer
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' }}
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          createInstaller: true

      - name: Upload Installer Artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: obs-websocket-windows-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}-installer
          path: ${{ github.workspace }}/plugin/release/obs-websocket-*.exe

  linux_build:
    name: 02 - Linux
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        arch: [x86_64]
    if: always()
    needs: [clang_check]
    outputs:
      commitHash: ${{ steps.setup.outputs.commitHash }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin
          submodules: recursive

      - name: Checkout obs-studio
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: obs-studio
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        working-directory: ${{ github.workspace }}/plugin
        id: setup
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          echo '::group::Set Commit Information'
          COMMIT_HASH=$(git rev-parse HEAD | cut -c1-9)
          COMMIT_TAG="$(git describe --exact-match --tags --abbrev=0 2> /dev/null || true)"

          if [[ -n "${COMMIT_TAG}" ]]; then
            VERSION_SUFFIX=$(echo "${COMMIT_TAG}" | cut -c7-21)
          else
            COMMIT_TAG="${COMMIT_HASH}-git"
            VERSION_SUFFIX="-${COMMIT_HASH}-git"
          fi
          echo '::endgroup::'

          echo "::set-output name=ccacheDate::$(date +"%Y-%m-%d")"
          echo "::set-output name=commitHash::${COMMIT_HASH}"
          echo "::set-output name=versionSuffix::${VERSION_SUFFIX}"

      - name: Restore Compilation Cache
        id: ccache-cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.ccache
          key: linux-${{ matrix.arch }}-ccache-plugin-${{ steps.setup.outputs.ccacheDate }}
          restore-keys: |
            linux-${{ matrix.arch }}-ccache-plugin-

      - name: Check for GitHub Labels
        id: seekingTesters
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          if [[ -n "$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s "${{ github.event.pull_request.url }}" | jq -e '.labels[] | select(.name == "Seeking Testers")')" ]]; then
            echo '::set-output name=found::true'
          else
            echo '::set-output name=found::false'
          fi

      - name: Build Plugin
        uses: ./plugin/.github/actions/build-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          versionSuffix: ${{ steps.setup.outputs.versionSuffix }}

      - name: Package Plugin
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo

      - name: Upload Build Artifact
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        uses: actions/upload-artifact@v3
        with:
          name: obs-websocket-linux-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}
          path: ${{ github.workspace }}/plugin/release/obs-websocket-*-linux-*.*

  macos_build:
    name: 02 - macOS
    runs-on: ${{ matrix.osVersion }}
    strategy:
      fail-fast: true
      matrix:
        arch: [x86_64, arm64, universal]
        osVersion: [macos-11, macos-12]
    if: always()
    needs: [clang_check]
    outputs:
      commitHash: ${{ steps.setup.outputs.commitHash }}
    env:
      CODESIGN_IDENT: '-'
      CODESIGN_IDENT_INSTALLER: ''
      MACOSX_DEPLOYMENT_TARGET: '10.15'
    defaults:
      run:
        shell: zsh {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin
          submodules: recursive

      - name: Checkout obs-studio
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: obs-studio
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        id: setup
        working-directory: ${{ github.workspace }}/plugin
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          print '::group::Clean Homebrew Environment'
          typeset -a to_remove=()

          for formula (speexdsp curl php) {
            if [[ -d ${HOMEBREW_PREFIX}/opt/${formula} ]] to_remove+=(${formula})
          }

          if (( #to_remove )) brew uninstall --ignore-dependencies ${to_remove}
          print '::endgroup::'

          print '::group::Set up code signing'
          if [[ '${{ secrets.MACOS_SIGNING_IDENTITY }}' != '' && \
                '${{ secrets.MACOS_INSTALLER_IDENTITY }}' != '' && \
                '${{ secrets.MACOS_SIGNING_CERT }}' != '' ]] {
            print '::set-output name=haveCodesignIdent::true'
          } else {
            print '::set-output name=haveCodesignIdent::false'
          }

          if [[ '${{ secrets.MACOS_INSTALLER_CERT_PASSWORD }}' != '' ]] {
            print '::set-output name=haveInstallerCert::true'
          } else {
            print '::set-output name=haveInstallerCert::false'
          }

          if [[ '${{ secrets.MACOS_NOTARIZATION_USERNAME }}' != '' && \
                '${{ secrets.MACOS_NOTARIZATION_PASSWORD }}' != '' ]] {
            print '::set-output name=haveNotarizationUser::true'
          } else {
            print '::set-output name=haveNotarizationUser::false'
          }
          print '::endgroup::'

          print '::group::Set Commit Information'
          COMMIT_HASH="${"$(git rev-parse HEAD)"[0,9]}"
          COMMIT_TAG="$(git describe --exact-match --tags --abbrev=0 2> /dev/null)"

          if [[ -n ${COMMIT_TAG} ]] {
            VERSION_SUFFIX="${COMMIT_TAG[7,14]}"
          } else {
            COMMIT_TAG="${COMMIT_HASH}-git"
            VERSION_SUFFIX="-${COMMIT_HASH}-git"
          }
          print '::endgroup::'

          print "::set-output name=ccacheDate::$(date +"%Y-%m-%d")"
          print "::set-output name=commitHash::${"$(git rev-parse HEAD)"[0,9]}"
          print "::set-output name=versionSuffix::${VERSION_SUFFIX}"

      - name: Restore Compilation Cache
        id: ccache-cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.ccache
          key: macos-${{ matrix.arch }}-ccache-plugin-${{ steps.setup.outputs.ccacheDate }}
          restore-keys: |
            macos-${{ matrix.arch }}-ccache-plugin-

      - name: Check for GitHub labels
        id: seekingTesters
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          if [[ -n "$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s "${{ github.event.pull_request.url }}" | jq -e '.labels[] | select(.name == "Seeking Testers")')" ]] {
            print '::set-output name=found::true'
          } else {
            print '::set-output name=found::false'
          }

      - name: Install Apple Developer Certificate
        if: ${{ github.event_name != 'pull_request' && steps.setup.outputs.haveCodesignIdent == 'true' }}
        uses: apple-actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
        with:
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.MACOS_SIGNING_CERT }}
          p12-password: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}

      - name: Install Apple Installer Certificate
        if: ${{ github.event_name != 'pull_request' && steps.setup.outputs.haveInstallerCert == 'true' }}
        uses: apple-actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
        with:
          keychain-password: ${{ github.run_id }}
          p12-file-base64: ${{ secrets.MACOS_INSTALLER_CERT }}
          p12-password: ${{ secrets.MACOS_INSTALLER_CERT_PASSWORD }}
          create-keychain: false

      - name: Set Signing Identity
        if: ${{ github.event_name != 'pull_request' && steps.setup.outputs.haveCodesignIdent == 'true' }}
        run: |
          ## CODESIGN IDENTITY SCRIPT
          print "CODESIGN_IDENT=${{ secrets.MACOS_SIGNING_IDENTITY }}" >> $GITHUB_ENV
          print "CODESIGN_IDENT_INSTALLER=${{ secrets.MACOS_INSTALLER_IDENTITY }}" >> $GITHUB_ENV

      - name: Build Plugin
        uses: ./plugin/.github/actions/build-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          codesign: 'true'
          codesignIdent: ${{ env.CODESIGN_IDENT }}
          versionSuffix: ${{ steps.setup.outputs.versionSuffix }}

      - name: Package Plugin
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          codesign: ${{ github.event_name != 'pull_request' && steps.setup.outputs.haveCodesignIdent == 'true' }}
          notarize: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' && steps.setup.outputs.haveCodesignIdent == 'true' }}
          codesignIdent: ${{ env.CODESIGN_IDENT }}
          installerIdent: ${{ env.CODESIGN_IDENT_INSTALLER }}
          codesignUser: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
          codesignPass: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}

      - name: Upload Build Artifact
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        uses: actions/upload-artifact@v3
        with:
          name: obs-websocket-macos-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}
          path: ${{ github.workspace }}/plugin/release/obs-websocket-*-macos-*.pkg

  make-release:
    name: 03 - Create and upload release
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [macos_build, linux_build, windows_build]
    defaults:
      run:
        shell: bash
    steps:
      - name: Get Metadata
        id: metadata
        run: |
          ## METADATA SCRIPT
          echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=date::$(date +"%Y-%m-%d")"
          echo '::set-output name=commitHash::${{ needs.windows_build.outputs.commitHash }}'

      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Generate Checksums
        run: |
          ## CHECKSUM GENERATION SCRIPT
          shopt -s extglob
          echo "### Checksums" > ${{ github.workspace }}/CHECKSUMS.txt
          for file in ${{ github.workspace }}/**/@(*.pkg|*.exe|*.deb|*.zip); do
            echo "    ${file##*/}: $(sha256sum "${file}" | cut -d " " -f 1)" >> ${{ github.workspace }}/CHECKSUMS.txt
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          draft: false
          prerelease: $(( needs.windows_build.outputs.versionSuffix != '' }}
          tag_name: ${{ steps.metadata.outputs.version }}
          name: "obs-websocket Build ${{ steps.metadata.outputs.version }}"
          body_path: ${{ github.workspace }}/CHECKSUMS.txt
          files: |
            ${{ github.workspace }}/obs-websocket-windows-x64-${{ steps.metadata.outputs.commitHash }}/*.zip
            ${{ github.workspace }}/obs-websocket-windows-x64-${{ steps.metadata.outputs.commitHash }}-installer/*.exe
            ${{ github.workspace }}/obs-websocket-windows-x86-${{ steps.metadata.outputs.commitHash }}/*.zip
            ${{ github.workspace }}/obs-websocket-windows-x86-${{ steps.metadata.outputs.commitHash }}-installer/*.exe
            ${{ github.workspace }}/obs-websocket-linux-x86_64-${{ steps.metadata.outputs.commitHash }}/*.deb
            ${{ github.workspace }}/obs-websocket-macos-x86_64-${{ steps.metadata.outputs.commitHash }}/*.pkg
            ${{ github.workspace }}/obs-websocket-macos-arm64-${{ steps.metadata.outputs.commitHash }}/*.pkg
            ${{ github.workspace }}/obs-websocket-macos-universal-${{ steps.metadata.outputs.commitHash }}/*.pkg
